site_name: zsh-vscodium Documentation
theme: "material"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: "#087da1"
    accent: "#00a889"
  font:
    text: "Source Sans Pro"

repo_name: "luismayta/zsh-vscodium"
repo_url: "https://github.com/luismayta/zsh-vscodium"
copyright: 'Copyright Â© 2020 <a href="https://hadenlabs.com">hadenlabs</a>'

google_analytics:
  - ""
  - "auto"
